language: python
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  # Run tests in various environments using tox.
  - tox
  # Run tests again with coverage.
  - py.test --cov-report=term-missing --cov=confmodel confmodel
after_success:
  - coveralls
